/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Badge = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const PlayerStats = IDL.Record({
  'streak' : IDL.Nat,
  'totalXp' : IDL.Nat,
  'badges' : IDL.Vec(Badge),
  'level' : IDL.Nat,
  'score' : IDL.Nat,
  'highScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getStats' : IDL.Func([], [PlayerStats], ['query']),
  'updateStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(Badge)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Badge = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const PlayerStats = IDL.Record({
    'streak' : IDL.Nat,
    'totalXp' : IDL.Nat,
    'badges' : IDL.Vec(Badge),
    'level' : IDL.Nat,
    'score' : IDL.Nat,
    'highScore' : IDL.Nat,
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getStats' : IDL.Func([], [PlayerStats], ['query']),
    'updateStats' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(Badge)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };